spring:
  application:
    name: ai-workbench-backend
  ai:
    ollama:
      base-url: http://localhost:11434
    openai:
      api-key: ${OPENAI_API_KEY}

workbench:
  mappings:
    chatMappings:
      OLLAMA:
        models:
          - llama3.2
          - mistral
          - deepseek-r1
          - deepseek-coder-v2
          - codellama
        handlerClass: com.emirant1.aiworkbenchbackend.chat.model.OllamaChatModelHandler
      OPENAI:
        models:
          - gpt-4o-mini
          - gpt-4o
        handlerClass: com.emirant1.aiworkbenchbackend.chat.model.OpenAiChatModelHandler